import { createClient } from '@supabase/supabase-js';
import { projectId, publicAnonKey } from '../../utils/supabase/info';

// Supabase configuration - using autogenerated connection info
const supabaseUrl = `https://${projectId}.supabase.co`;
const supabaseAnonKey = publicAnonKey;

// Create Supabase client
export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Types for database tables
export interface Database {
  public: {
    Tables: {
      projects: {
        Row: {
          id: string;
          title: string;
          category: 'websites' | 'apps' | 'social' | 'branding' | 'research';
          description: string;
          image: string;
          tags: string[];
          full_description: string | null;
          challenge: string | null;
          solution: string | null;
          results: string[] | null;
          timeline: string | null;
          client: string | null;
          role: string | null;
          gallery: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          category: 'websites' | 'apps' | 'social' | 'branding' | 'research';
          description: string;
          image: string;
          tags?: string[];
          full_description?: string | null;
          challenge?: string | null;
          solution?: string | null;
          results?: string[] | null;
          timeline?: string | null;
          client?: string | null;
          role?: string | null;
          gallery?: string[] | null;
        };
        Update: {
          title?: string;
          category?: 'websites' | 'apps' | 'social' | 'branding' | 'research';
          description?: string;
          image?: string;
          tags?: string[];
          full_description?: string | null;
          challenge?: string | null;
          solution?: string | null;
          results?: string[] | null;
          timeline?: string | null;
          client?: string | null;
          role?: string | null;
          gallery?: string[] | null;
        };
      };
      testimonials: {
        Row: {
          id: string;
          name: string;
          role: string;
          company: string;
          content: string;
          rating: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          role: string;
          company: string;
          content: string;
          rating: number;
        };
        Update: {
          name?: string;
          role?: string;
          company?: string;
          content?: string;
          rating?: number;
        };
      };
      experience: {
        Row: {
          id: string;
          company: string;
          role: string;
          period: string;
          description: string;
          achievements: string[];
          current: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company: string;
          role: string;
          period: string;
          description: string;
          achievements?: string[];
          current?: boolean;
        };
        Update: {
          company?: string;
          role?: string;
          period?: string;
          description?: string;
          achievements?: string[];
          current?: boolean;
        };
      };
    };
  };
}
